/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 75518b88fd7af2a80943c77d7066cf96)
interface __BaseEnv_Env {
	DB: D1Database;
	SYNC_QUEUE: Queue;
	ASSETS: Fetcher;
	ECWID_MODE: string;
	LIVE_SYNC_ENABLED: string;
	ORDER_SYNC_ENABLED: string;
	ECWID_STORE_ID: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ADMIN_EMAILS: string;
	STAFF_EMAILS: string;
	INVENTORY_ENABLED: string;
	ECWID_TOKEN: string;
	ECWID_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ECWID_MODE" | "LIVE_SYNC_ENABLED" | "ORDER_SYNC_ENABLED" | "ECWID_STORE_ID" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ADMIN_EMAILS" | "STAFF_EMAILS" | "INVENTORY_ENABLED" | "ECWID_TOKEN" | "ECWID_CLIENT_SECRET">> {}
}
